# Generated by Django 6.0.3 on 2026-03-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="file_size",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
